name             'testbook'
maintainer       'Andrii Starodubets'
maintainer_email 'astarodubets@gmail.com'
license          'All rights reserved'
description      'Installs/Configures testbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'testbook'
depends 'apache2'
depends 'firewall'
depends 'jenkins'
depends 'java'
depends 'tomcat'
depends 'hostsfile'
depends 'hostname'
depends 'nginx'
